### ISSUE TITLE
Is there any way to use an ENV var to define the index name?

### ISSUE THREAD

**Issue by alexwhb** [Davide-Gheri/nestjs-algoliasearch#92]
This is a fantastic resource. Thank you for putting the time in to build it. I have one question... is there a way to using your .env file to define your index name instead of hard coding it? in my use case the index name can change. I've tried using process.env.SOME_ENV_NAME and that causes the nest app to crash. Pretty sure the .env is getting parsed after the algolia module is getting initialized. 

Thanks for your time.

**Comment by korifey91** [comment]
the same for me

**Comment by Davide-Gheri** [comment]
Hi, you could manually get the provider using `@nestjs/core` `ModuleRef `, it should work:

```
import { getIndexToken } from 'nestjs-algoliasearch';

@Injectable()
export class SomeService implements OnModuleInit {
  private searchIndex: SearchIndex;

  constructor(
    private readonly ref: ModuleRef,
  ) {}

  onModuleInit() {
    this.searchIndex = this.ref.get(getIndexToken(process.env.INDEX_NAME));
  }
}

```

Please refer to Nest documentation https://docs.nestjs.com/fundamentals/module-ref to more info
